name: transcribe
description: "Transcribe Audio"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  responsive_sizer: ^3.3.1
  hooks_riverpod: ^2.6.1
  http: ^1.2.2
  # fluttertoast: ^8.2.8
  flutter_styled_toast: ^2.2.1
  flutter_hooks: ^0.20.5
  purchases_flutter: ^8.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  share_plus: ^10.1.1
  in_app_review: ^2.0.9
  bmprogresshud: ^1.0.3
  flutter_native_splash: ^2.2.19
  dio: ^5.7.0
  # flutter_inappwebview: ^6.1.5
  internet_connection_checker: ^1.0.0
  introduction_screen: ^3.1.14
  speech_to_text: ^7.0.0
  lottie: ^3.1.3
  file_picker: ^8.1.7
  record: ^5.0.5
  open_store: ^0.5.0
  # flutter_tts: ^4.2.0
  package_info_plus: ^8.1.0
  flutter_dotenv: ^5.2.1
  quick_actions: ^1.0.8
  slack_notifier: ^1.4.0
  # rive: ^0.13.15
  path: ^1.9.0
  deepgram_speech_to_text: ^2.3.2
  audioplayers: ^6.1.0
  hugeicons: ^0.0.7
  selectable_autolink_text: ^2.6.0
  intl: ^0.19.0
  macos_ui: ^2.0.9
  window_manager: ^0.4.2
  # firebase_core: ^3.10.0
  # firebase_crashlytics: ^4.3.0
  # firebase_analytics: ^11.4.0
  rename: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.14.3
  build_runner: ^2.3.3
  hive_generator: ^2.0.0
  msix: ^3.16.8

flutter_native_splash:
  color: "#5545FF"
  image: 'assets/images/appicon.png'
  icon_background_color: "#5546FF"
  windows: true

flutter_launcher_icons:
  windows:
    generate: true
    image_path: "assets/images/appicon.png"
    icon_size: 48 # min:48, max:256, default: 48

msix_config:
  display_name: Transcribe Audio - Speech To Text & AI Voice Note Taker
  publisher_display_name: Kayma Tech
  publisher: CN=6D7B6037-2660-4B30-BC26-AECC23D4D646
  identity_name: KaymaTech.Transcriber-SpeechToText
  msix_version: 1.0.2.0
  trim_logo: false
  logo_path: assets/images/appicon.png
  capabilities: "internetClient"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lottie/
    - assets/rive/
    - .env
  fonts:
    - family: Karla
      fonts:
        - asset: assets/fonts/Karla-Regular.ttf
        - asset: assets/fonts/Karla-Bold.ttf
          weight: 700
        - asset: assets/fonts/Karla-Italic.ttf
          style: italic
        - asset: assets/fonts/Karla-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Karla-Light.ttf
          weight: 300
        - asset: assets/fonts/Karla-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Karla-Medium.ttf
          weight: 500
        - asset: assets/fonts/Karla-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Karla-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Karla-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Karla-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Karla-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Karla-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Karla-ExtraLightItalic.ttf
          weight: 200
          style: italic

