// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:transcribe/models/audiomodel.dart';
import 'package:transcribe/models/listaudiomodel.dart';
import 'package:transcribe/models/paragraph.dart';
import 'package:transcribe/models/paragraphs.dart';
import 'package:transcribe/models/responsemodel.dart';
import 'package:transcribe/models/sentence.dart';
import 'package:transcribe/models/usermodel.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AudioModelAdapter());
    registerAdapter(ParagraphAdapter());
    registerAdapter(ParagraphsAdapter());
    registerAdapter(ResponsemodelAdapter());
    registerAdapter(SentenceAdapter());
    registerAdapter(UserAdapter());
    registerAdapter(UserAudioHistoryAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AudioModelAdapter());
    registerAdapter(ParagraphAdapter());
    registerAdapter(ParagraphsAdapter());
    registerAdapter(ResponsemodelAdapter());
    registerAdapter(SentenceAdapter());
    registerAdapter(UserAdapter());
    registerAdapter(UserAudioHistoryAdapter());
  }
}
